# proxy domains
[proxy]
"domain_suffix" = [
    # Apple
    "amp-api-edge.apps.apple.com",
    "push.apple.com",
    "inappcheck.itunes.apple.com",
    "app.adjust.com",

    # Google 
    "googleapis.com,
    "googleapis.cn",
    "google.cn",

    # Microsoft
    "bing.com",
    "windows.com",
    "windows.net",
    "office.com",
    "microsoft.com",
    "live.com",
    "onenote.com",
    "contentsync.onenote.com",
    "hierarchyapi.onenote.com",
    "microsoftonline.com",
    "office.net",
    "sharepoint.com",
    "1drv.com",

    # Nexon
    "nexoncdn.co.kr",
    "nexon.com",
    "nexon.io",

    # LinkedIn
    "linkedin.com",

    # Leetcode
    "leetcode.cn",

    # Spotify
    "spotify.com",
    "spotifycdn.com",
    "scdn.co",
    "cookielaw.org",

    # Cloudflare
    "onetrust.com",

    # Talkatone
    "inner-active.mobi",
    "tktn.be",
    "mobilefuse.com",
    "kochava.com",
    "cohere.com",
    "ip-api.com",
    "talkatone.com",
    "tktn.at",
    "agkn.com",
    "kavedit.site",

    # Github
    "githubusercontent.com",    
]
